name: Remote ssh
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd Xatu_Bot
          git pull
        host: ${{ secrets.AWS_IP }}
        args: -i ../FE_Bot.pem
